name: Mac

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  macos_lateset:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    env:
      FC: gfortran

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel 10