name: Windows

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mingw:
    runs-on: windows-2019
    strategy:
      matrix:
        architecture: [x64]
        build_type: [Debug, Release]
    env:
      FC: gfortran
    steps:
      - uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.architecture }}
          version: 12.2.0 # https://github.com/egor-tensin/setup-mingw/issues/14

      - name: Run Cmake 
        run: cmake -S . -B build -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -A ${{ matrix.architecture }}

      - name: Build
        run: cmake --build build  --verbose
